# Nom ......... : Makefile
# Rôle ........ : Compile projet
# Auteur ...... : Avrile Floro 
# Version ..... : V0.1 du 25/10/23
# Licence ..... : réalisé dans le cadre du cours de SE
# Usage : Pour exécuter : make (depuis le répertoire)

all:
	gcc -Wall projet_co-main.c and_monexit.c redirection.c redir_in_pipe.c cn-decouper.c moncd.c pipe.c man.c -lreadline -o projet 

clean:
	rm -f projet